### ISSUE TITLE
Support Python <3.11

### ISSUE THREAD

**Issue by bfontaine** [click-contrib/click-aliases#11]
Hello,
Is there any reason this [requires Python 3.11](https://github.com/click-contrib/click-aliases/blob/c98ac3646bf4b266a36bdf13e91a113e9a8693d6/pyproject.toml#L11)? Click supports Python 3.7+.

**Comment by abegong** [comment]
I have the same question.

**Comment by rbonthond** [comment]
I've merged it

**Comment by amotl** [comment]
That was quick, thanks a stack!
